# Generated by Django 3.2.13 on 2022-08-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=512, verbose_name='Mavzu')),
                ('title_uz', models.CharField(max_length=512, null=True, verbose_name='Mavzu')),
                ('title_uzb', models.CharField(max_length=512, null=True, verbose_name='Mavzu')),
                ('title_ru', models.CharField(max_length=512, null=True, verbose_name='Mavzu')),
                ('title_en', models.CharField(max_length=512, null=True, verbose_name='Mavzu')),
                ('content', models.TextField(verbose_name='Matni')),
                ('content_uz', models.TextField(null=True, verbose_name='Matni')),
                ('content_uzb', models.TextField(null=True, verbose_name='Matni')),
                ('content_ru', models.TextField(null=True, verbose_name='Matni')),
                ('content_en', models.TextField(null=True, verbose_name='Matni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_data_created_by', to=settings.AUTH_USER_MODEL)),
                ('menu', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='menu.menu', verbose_name='Menyu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_data_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ma'lumotnoma",
                'verbose_name_plural': "Ma'lumotnomalar",
                'db_table': 'data',
            },
        ),
    ]
