# Generated by Django 3.2.13 on 2022-07-05 10:43

import config.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_uzb', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('content_uz', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_uzb', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_ru', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_en', models.TextField(null=True, verbose_name='Mazmuni')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Havola')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/organization', validators=[config.validation.validate_file_extension], verbose_name='Rasm')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_organization_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_organization_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tashkilot ',
                'verbose_name_plural': 'Tashkilotlar',
                'db_table': 'organization',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='AccountOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=510, verbose_name='Hisobot nomlanishi')),
                ('title_uz', models.CharField(max_length=510, null=True, verbose_name='Hisobot nomlanishi')),
                ('title_uzb', models.CharField(max_length=510, null=True, verbose_name='Hisobot nomlanishi')),
                ('title_ru', models.CharField(max_length=510, null=True, verbose_name='Hisobot nomlanishi')),
                ('title_en', models.CharField(max_length=510, null=True, verbose_name='Hisobot nomlanishi')),
                ('account', models.FileField(blank=True, null=True, upload_to='files/organization', verbose_name='Hisobot fayli')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.organization')),
            ],
        ),
    ]
