# Generated by Django 3.2.13 on 2022-06-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['index'], 'verbose_name': 'Tashkilot ', 'verbose_name_plural': 'Tashkilotlar'},
        ),
    ]
