# Generated by Django 3.2.13 on 2022-08-02 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='lider_name',
            field=models.CharField(default=datetime.date(2022, 8, 2), max_length=256, verbose_name='Boshqaruvchi nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='lider_position',
            field=models.CharField(default=datetime.date(2022, 8, 2), max_length=256, verbose_name='Boshqaruvchisi lavozimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='reception_days',
            field=models.CharField(default=datetime.date(2022, 8, 2), max_length=256, verbose_name='Qabul vaqtlari'),
            preserve_default=False,
        ),
    ]
