# Generated by Django 3.2.13 on 2022-07-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_uzb', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('phone', models.TextField(verbose_name='Telefon')),
                ('email', models.TextField(verbose_name='E-mail')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('address_uzb', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('transport', models.TextField(verbose_name='Transport')),
                ('transport_uz', models.TextField(null=True, verbose_name='Transport')),
                ('transport_uzb', models.TextField(null=True, verbose_name='Transport')),
                ('transport_ru', models.TextField(null=True, verbose_name='Transport')),
                ('transport_en', models.TextField(null=True, verbose_name='Transport')),
                ('reception_days', models.TextField(verbose_name='Qabul kunlari')),
                ('reception_days_uz', models.TextField(null=True, verbose_name='Qabul kunlari')),
                ('reception_days_uzb', models.TextField(null=True, verbose_name='Qabul kunlari')),
                ('reception_days_ru', models.TextField(null=True, verbose_name='Qabul kunlari')),
                ('reception_days_en', models.TextField(null=True, verbose_name='Qabul kunlari')),
            ],
            options={
                'verbose_name': "Bog'lanish",
                'verbose_name_plural': "Bog'lanish",
                'db_table': 'contact',
            },
        ),
    ]
