# Generated by Django 3.2.13 on 2022-07-05 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import menu.models
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=500, verbose_name='Nomlanishi')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('title_uzb', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('type', models.CharField(choices=[('singlepage', 'Bitta sahifa'), ('post', 'Post'), ('attachment', "Ilovali ro'yxat"), ('menu', 'Menyu'), ('photogallery', 'Foto galereya'), ('videogallery', 'Video galereya'), ('equipments', 'Asbob uskunalar'), ('internship', 'Stajirovka'), ('other', 'Boshqa')], default=menu.models.TypeList['other'], max_length=100, verbose_name='Turi')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Havola')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami')),
                ('note', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Izoh')),
                ('note_uz', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Izoh')),
                ('note_uzb', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Izoh')),
                ('note_ru', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Izoh')),
                ('note_en', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Izoh')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_menu_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_menu', to='menu.menu', verbose_name='YuqoriMenyu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_menu_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menyu',
                'verbose_name_plural': 'Menyu',
                'db_table': 'menu',
                'ordering': ['index'],
            },
        ),
    ]
